config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path("admin/", admin.site.urls),
]

urlpatterns = [
    path("zunsm29qmj/", admin.site.urls),
    path("map/", include("map.urls", namespace="map")),
    path("bakery/", include("bakeries.urls", namespace="bakeries")),
    path("post/", include("posts.urls", namespace="posts")),
    path("", include("users.urls", namespace="users")),
    url(
        r"media/(?P<path>.*)$",
        serve,
        {
            "document_root": settings.MEDIA_ROOT,
        },
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

map/urls.py
from django.urls import path
from . import views

app_name = "map"

urlpatterns = [
    path("", views.main_map_view, name="main_map"),
    path("region-api/", views.get_region_api, name="get_region_api"),
    path("bakery-list-api/", views.get_bakery_list_api, name="get_bakery_list_api"),
    path(
        "bakery-detail-api/", views.get_bakery_detail_api, name="get_bakery_detail_api"
    ),
    path(
        "bakery-detail-reviews-api/",
        views.get_bakery_detail_reviews_api,
        name="get_bakery_detail_reviews_api",
    ),
    path("bakery-delete-review/", views.ajax_delete_review, name="ajax_delete_review"),
]

posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path("", views.post_list, name="list"),
    # 프론트앤드 작업할때는 "1/"로 해놨지만, 나중에는 "<int:pk>/"로 변경예정"
    path("my/", views.post_my, name="my"),
    path("<int:post_id>/", views.post_detail, name="detail"),
    path("write/", views.post_write, name="write"),
    path("<int:post_id>/update/", views.post_update, name="update"),
    path("<int:post_id>/delete/", views.post_delete, name="delete"),
    path(
        "<int:post_id>/addcomment/",
        views.add_comment_to_post,
        name="add_comment_to_post",
    ),
    path(
        "<int:post_id>/comment/<int:comment_id>/delete",
        views.comment_delete,
        name="comment_delete",
    ),
    path("ajax_scrap/", views.ajax_scrap, name="ajax_scrap"),
    path("scrap/", views.scrap_post_list, name="scrap"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    # 배포시에는 index페이지 삭제
    # path("", views.index),
    path("user/profile/", views.profile_view, name="profile"),
    path("user/profile-update/", views.profile_update, name="profile_update"),
    path("", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("signup/", views.signup, name="signup"),
    path("user/login/kakao/", views.kakao_login, name="kakao-login"),
    path("user/login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
    path("imageupdate/", views.profileimage_update, name="imageupdate"),
    path("developers/", views.developers, name="developers"),
]

posts/models.py
from django.db import models
from django.db.models.signals import post_delete
from django.dispatch import receiver
from users import models as user_models
from bakeries import models as bakery_models
import datetime, os, random

# Post모델의 image필드(게시글에 들어갈 사진)의 경로설정 함수
def photo_path(instance, filename):
    basefilename, file_extension = os.path.splitext(filename)
    chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890"
    randomstr = "".join((random.choice(chars)) for x in range(10))
    return "post/image/{postid}/{randomstring}{ext}".format(
        postid=instance.id,
        basename=basefilename,
        randomstring=randomstr,
        ext=file_extension,
    )


class Post(models.Model):
    title = models.CharField(max_length=20)
    body = models.CharField(max_length=500)
    created_date = models.DateTimeField(auto_now_add=True)
    views = models.PositiveIntegerField(default=0)
    user = models.ForeignKey(
        user_models.User, related_name="posts", on_delete=models.CASCADE
    )
    photo = models.ImageField(upload_to=photo_path, blank=True)
    scraped = models.ManyToManyField(
        user_models.User, blank=True, related_name="scraped"
    )

    def comments_count(self):
        pass

    @property
    def click(self):
        self.views += 1
        self.save()

    def __str__(self):
        return self.title


# Post 객체 삭제시, photo필드의 사진파일도 같이 삭제됨
@receiver(post_delete, sender=Post)
def submission_delete(sender, instance, **kwargs):
    instance.photo.delete(False)


class Comment(models.Model):
    body = models.CharField(max_length=300)
    created_date = models.DateTimeField(auto_now=True)
    post = models.ForeignKey("Post", related_name="comments", on_delete=models.CASCADE)
    user = models.ForeignKey(
        user_models.User,
        related_name="comments",
        on_delete=models.CASCADE,
    )
    target_comment = models.ForeignKey(
        "self",
        on_delete=models.CASCADE,
        related_name="comments",
        default=None,
        blank=True,
        null=True,
    )  # 댓글의 답글이 달릴경우 생성되는 필드. 없으면 빈상태로 DB에 저장

    def __str__(self):
        if self.target_comment == None:
            return f"{self.post} | {self.body[:15]}..."
        else:
            return f"{self.post} | [답글]{self.body[:15]}..."

posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "body", "photo"]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["body"]

posts/views.py
import json
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.conf import settings
from . import models as post_models
from .models import Comment
from .forms import PostForm
from .forms import CommentForm

# Create your views here.


def post_list(request):
    all_posts = post_models.Post.objects.all().order_by("-created_date")
    all_posts = all_posts[:30]
    sorted_posts = post_models.Post.objects.all().order_by("-views")
    top3_posts = sorted_posts[:3]
    return render(
        request,
        "posts/post_list.html",
        {"all_posts": all_posts, "top3_posts": top3_posts},
    )


def post_my(request):
    return render(request, "posts/my_post_list.html")


def post_detail(request, post_id):
    aws_url = settings.MY_AWS_URL
    post_detail = get_object_or_404(post_models.Post, pk=post_id)
    comments = post_detail.comments.filter(target_comment__isnull=True)
    try:
        is_scraped = request.user.scraped.filter(pk=post_id).exists()
    except:
        is_scraped = ""

    if request.method == "POST":
        form = CommentForm(request.POST, request.FILES)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post_detail
            comment.user = request.user
            if request.POST.get("pk") is not None:
                comment.target_comment = Comment.objects.get(
                    pk=int(request.POST.get("pk"))
                )
            comment.save()

            return redirect(reverse("posts:detail", kwargs={"post_id": post_id}))
    else:
        form = CommentForm()
    return render(
        request,
        "posts/post_detail.html",
        {
            "post_detail": post_detail,
            "comments": comments,
            "form": form,
            "is_scraped": is_scraped,
            "aws_url": aws_url,
        },
    )


def post_write(request):
    if request.user.is_anonymous:
        return redirect("users:login")
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect("/post/")

    else:
        form = PostForm()
    return render(request, "posts/post_write.html", {"form": form})


def post_update(request, post_id):
    post = get_object_or_404(post_models.Post, pk=post_id)
    if post.user != request.user:
        raise Http404("권한이 없습니다.")
    form = PostForm(request.POST, request.FILES, instance=post, auto_id=True)

    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect("/post/" + str(post_id))
    else:
        form = PostForm(instance=post)
        return render(request, "posts/post_update.html", {"form": form})


def post_delete(request, post_id):
    post = post_models.Post.objects.get(pk=post_id)
    if post.user == request.user:
        post.delete()
        return redirect("/post/")
    else:
        raise Http404("권한이 없습니다.")


def add_comment_to_post(request, post_id):
    post = get_object_or_404(post_models.Post, pk=post_id)
    if request.method == "POST":
        form = CommentForm(request.POST, request.FILES)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.user = request.user
            comment.save()
            return redirect("/post/" + str(post_id))
    else:
        form = CommentForm()
    return render(request, "posts/post_add_comment.html", {"form": form})


def comment_delete(request, post_id, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)

    if comment.user != request.user:
        raise Http404("권한이 없습니다.")
    else:
        comment.delete()
        return redirect("/post/" + str(post_id))


@login_required
@require_POST
def ajax_scrap(request):
    if request.method == "POST":
        user = request.user
        pk = request.POST.get("pk", None)
        post = post_models.Post.objects.get(pk=pk)
        if user.scraped.filter(pk=pk).exists():
            post.scraped.remove(user)
        else:
            post.scraped.add(user)
    context = {}
    return HttpResponse(json.dumps(context), content_type="application/json")


def scrap_post_list(request):
    user = request.user
    posts = post_models.Post.objects.filter(scraped=user)
    posts = posts.order_by("-created_date")
    return render(request, "posts/scrap_post_list.html", {"posts": posts})

templates/posts/my_post_list.html
{% extends 'base.html' %}
{% load static %}

<!-- 홈페이지 타이틀 -->
{% block title %}
내가 쓴 글
{% endblock title %}


<!-- 개별적인 css/link태그 추가 -->
{% block css %}
<link rel="stylesheet" href="{% static 'posts/css/post_list.css' %}">
{% endblock css %}


{% block header %}
<div class="header__wrapper">
    <div class="header__leftbox">
        <a href="{% url 'users:profile' %}"><img class="left_arrow" src="{% static 'core/img/left_arrow.png' %}"
                alt="left_arrow icon"></a>
    </div>
    <div class="header__midbox">
        <span class="header__title">내가 쓴 글</span>
    </div>
    <div class="header__rightbox">
    </div>
</div>
{% endblock header %}


{% block content %}
{% if user.posts.all %}
<div class="post_list_bigbox">
    <div class="post_list_box">
        {% for post in user.posts.all %}
        <a href="{% url 'posts:detail' post.id %}">
            <div class="user_post_box">
                <span class="user_post_information">
                    <div class="user_post_title">{{post.title}}</div>
                    <div class="user_post_title_underbox">
                        <span>{{post.user.nickname}}</span>
                        <span>{{post.created_date|date:"Y.m.d f"}}</span>
                        <span>{{post.views}}</span>
                    </div>
                </span>
                <span class="user_post_comment">
                    <img src="{% static 'posts/img/comment.png' %}">
                    <div>{{post.comments.count}}</div>
                </span>
            </div>
        </a>
        {% endfor %}
    </div>
</div>
{% else %}
<div class="no_exist">
    <span>작성한 게시글이 없습니다!</span>
</div>
{% endif %}
{% endblock content %}

templates/posts/post_add_comment.html
{% extends 'base.html' %}
{% load static %}

<!-- 홈페이지 타이틀 -->
{% block title %}
게시글
{% endblock title %}


<!-- 개별적인 css/link태그 추가 -->
{% block css %}
<link rel="stylesheet" href="{% static 'posts/css/post_write.css' %}">
{% endblock css %}


{% block header %}
<div class="header__wrapper">
    <div class="header__leftbox">
        <img class="left_arrow" src="{% static 'core/img/left_arrow.png' %}" alt="left_arrow icon">
    </div>
    <div class="header__midbox">
        <span class="header__title">댓글쓰기</span>
    </div>
    <div class="header__rightbox"></div>
</div>
{% endblock header %}


{% block content %}
<form method="POST" class="post-form" enctype="multipart/form-data">
    
{% csrf_token %}
<div class="post_write_contents_box">{{ form.body }}</div>
<!-- 글쓰기 이미지추가&등록 박스 -->
<div class="post_write_submit_img_box">
    <span class="post_write_img_box">
        {{ form.photo }}
        <!-- <img src="{% static 'posts/img/cameraimg.png' %}" class="post_write_camera"> -->
    </span>
    <input class="post_write_submit" type="submit" value="등록">
</div>

</form>
{% endblock content %}

templates/posts/post_detail.html
{% extends 'base.html' %}
{% load static %}

<!-- 홈페이지 타이틀 -->
{% block title %}
게시글
{% endblock title %}


<!-- 개별적인 css/link태그 추가 -->
{% block css %}
<link rel="stylesheet" href="{% static 'posts/css/post_detail.css' %}">
<script src="https://code.jquery.com/jquery-latest.min.js"></script>
{% endblock css %}


{% block header %}
<div class="header__wrapper">
    <div class="header__leftbox">
        <a href="{% url 'posts:list' %}"><img class="left_arrow" src="{% static 'core/img/left_arrow.png' %}"
                alt="left_arrow icon"></a>
    </div>
    <div class="header__midbox">
        <span class="header__title">빵 커뮤니티</span>
    </div>
    <div class="header__rightbox">
        <!-- <img class="post_icon" src="{% static  'posts/img/menu.png' %}"> -->
    </div>
</div>
{% endblock header %}


{% block content %}
<div class="post_detail_allbox">
    <!-- 게시물 정보 및 유저 정보 박스 -->
    <div class="post_user_information">
        <div style="background-image:url({{post_detail.user.avatar.url}})" class="post_detail_profile_img"></div>
        <span class="post_user_information_smallbox">
            <span class="post_user_nickname">{{post_detail.user.nickname}}</span>
            <span class="post_time_pageview">
                <span class="post_detail_time">{{post_detail.created_date|date:"Y.m.d f"}}</span>
                <span class="post_detail_pageview">조회 {{post_detail.views}}</span>
                <span class="views_count">{{post_detail.click}}</span>
            </span>
        </span>
    </div>

    <!-- 게시물 내용 박스 -->
    <div class="post_detail_contents_box">
        <div class="post_detail_title_scrap">
            <span class="post_detail_title">{{post_detail.title}}</span>

            {% if user.is_authenticated %}
            {% if is_scraped %}
            <span class="post_detail_scrap jsScrap border-color-gold" onclick="clickScrap()">
                <img class="jsScrapImg" src="{% static 'posts/img/star.png' %}">
                <span class="post_detail_scrap_text jsScraptext text-color-gold">스크랩</span>
            </span>
            {% else %}
            <span class="post_detail_scrap jsScrap" onclick="clickScrap()">
                <img class="jsScrapImg" src="{% static 'posts/img/white_star.png' %}">
                <span class="post_detail_scrap_text jsScraptext">스크랩</span>
            </span>
            {% endif %}
            {% else %}
            <span class="post_detail_scrap jsScrap">
                <img class="jsScrapImg" src="{% static 'posts/img/white_star.png' %}">
                <span class="post_detail_scrap_text jsScraptext">스크랩</span>
            </span>
            {% endif %}

        </div>
        <div class="post_detail_contents">{{post_detail.body}}</div>
        <div class="post_detail_photo">
            {% if post_detail.photo %}
            <img src="{{post_detail.photo.url}}" alt="detail_img">
            {% endif %}
        </div>
        <!-- 수정삭제 -->
        <div class="post_detail_ud_box">
            {% if post_detail.user == request.user %}
            <a href="{% url 'posts:update' post_detail.id %}">
                <input class="post_detail_update_delete" type="button" style="border-radius: 3px;" value="수정">
            </a>
            <a href="{% url 'posts:delete' post_detail.id %}">
                <input class="post_detail_update_delete" type="button" style="border-radius: 3px;" value="삭제">
            </a>
            {% endif %}
        </div>


        <div>
            <!-- 댓글 상단 박스 -->
            <div class="post_detail_comment_top_box">
                <span class="post_detail_comment_top">댓글</span>
                <span class="post_detail_comment_count">{{post.comments_count}}</span>
            </div>

            <!-- 댓글 박스 -->
            {% for comment in comments reversed %}
            <div class="post_detail_comment_box">
                <div class="post_detail_comment_smallbox">
                    <span style="background-image:url({{comment.user.avatar.url}})"
                        class="post_detail_profile_img"></span>
                    <span class="post_detail_comment_information">
                        <div class="post_detail_comment_nickname_time">
                            <span class="post_detail_comment_nickname">{{comment.user.nickname}}</span>
                            <span class="post_detail_comment_time">{{comment.created_date|date:"Y.m.d f"}}</span>
                            {% if comment.user == request.user %}
                            <a class="post_detail_comment_delete"
                                href="{% url 'posts:comment_delete' post_detail.id comment.id %}"><img
                                    src="{% static 'posts/img/trash.png' %}"></a>
                            {% endif %}
                        </div>
                        <div class="post_detail_comment_contents">{{comment.body}}</div>
                    </span>
                </div>
                {% for recomment in comment.comments.all reversed  %}
                <div class="post_detail_comment_box recomment">
                    <img class="recomment_arrow" src="{% static 'posts/img/arrow.png' %}" alt="arrow image">
                    <div class="post_detail_comment_smallbox">
                        <span style="background-image:url({{recomment.user.avatar.url}})"
                            class="post_detail_profile_img"></span>
                        <span class="post_detail_comment_information">
                            <div class="post_detail_comment_nickname_time">
                                <span class="post_detail_comment_nickname">{{recomment.user.nickname}}</span>
                                <span class="post_detail_comment_time">{{recomment.created_date|date:"Y.m.d f"}}</span>
                                {% if recomment.user == request.user %}
                                <a class="post_detail_comment_delete"
                                    href="{% url 'posts:comment_delete' post_detail.id recomment.id %}"><img
                                        src="{% static 'posts/img/trash.png' %}"></a>
                                {% endif %}
                            </div>
                            <div class="post_detail_comment_contents">{{recomment.body}}</div>
                        </span>
                    </div>
                </div>
                {% endfor %}

                {% if user.is_authenticated %}
                <div class="post_detail_leave_a_comment">
                    <span class="jsTargetRecommentButton {{comment.pk}}" value='{{comment.pk}}'
                        onclick="addRecoment(event)">답글
                        쓰기</span>
                </div>
                {% endif %}
            </div>
            {% empty %}
            <p> </p>
            {% endfor %}
        </div>


    </div>


</div>
{% endblock content %}

{% block bottom_icons %}
<div class="bottom_blank bottom_height"></div>
{% if user.is_authenticated %}
<form method="POST" class="post-form" enctype="multipart/form-data">
    {% csrf_token %}
    <span class="post_detail_add_comment">{{ form.body }}</span>
    <input class="post_comment_submit" type="submit" value="등록" style="border-radius: 3px;">
</form>
{% else %}
<div style="font-size:14px;" class="post-form"><strong><a href="{% url 'users:login' %}">로그인</a></strong>&nbsp; 후에 댓글작성이
    가능합니다</div>
{% endif %}
{% endblock bottom_icons %}

{% block script %}
<script>
    const csrf = "{{ csrf_token }}";
    const ajaxScrapUrl = "{% url 'posts:ajax_scrap' %}";
    const postPK = "{{ post_detail.pk }}"
    const awsURL = "{{ aws_url }}"
</script>
<script src="{% static 'posts/js/scrap.js' %}"></script>
<script src="{% static 'posts/js/addRecomment.js' %}"></script>

{% endblock script %}

templates/posts/post_list.html
{% extends 'base.html' %}
{% load static %}

<!-- 홈페이지 타이틀 -->
{% block title %}
게시판
{% endblock title %}


<!-- 개별적인 css/link태그 추가 -->
{% block css %}
<link rel="stylesheet" href="{% static 'posts/css/post_list.css' %}">
{% endblock css %}

{% block header %}
<div class="header__wrapper">
    <div class="header__leftbox">
    </div>
    <div class="header__midbox">
        <span class="header__title">빵 커뮤니티</span>
    </div>
    <div class="header__rightbox">
        <!-- <img class="search_icon" src="{% static  'core/img/search.png' %}" alt="search icon"> -->
        {% if user.is_authenticated %}
        <a href="{% url 'posts:write' %}"><img class="post_icon" src="{% static  'core/img/post.png' %}"
                alt="post icon"></a>
        {% else %}
        <img class="post_icon" src="{% static  'core/img/post.png' %}" alt="post icon" onclick="button1_click();">
        <script>
            function button1_click() {
                alert("로그인이 필요합니다.");
            }
        </script>
        {% endif %}
    </div>
</div>
{% endblock header %}


{% block content %}
<div class="post_list_bigbox">
    <!-- hot 게시물 박스 -->
    <div class="hot_post_box">
        <div class="hot_post_box_title">HOT 게시물</div>
        {% for top_post in top3_posts %}
        <a href="{% url 'posts:detail' top_post.id %}" class="hot_post_list">
            <span class="hot_post_list_title">{{top_post.title}}</span>
            <span class="hot_post_list_page_view">조회 {{top_post.views}}</span>
        </a>
        {% endfor %}

    </div>
    <!-- 인기순/최신순 박스 -->
    <!-- <div class="post_list_popular_latest">
        <span class="post_list_popular">인기순</span>
        <span class="post_list_latest">최신순</span>
    </div> -->
    <!-- 게시물 리스트 박스 -->
    <div class="post_list_box">
        {% for post in all_posts %}
        <a href="{% url 'posts:detail' post.id %}">
            <div class="user_post_box">
                <span class="user_post_information">
                    <div class="user_post_title">{{post.title}}</div>
                    <div class="user_post_title_underbox">
                        <span>{{post.user.nickname}}</span>
                        <span>{{post.created_date|date:"Y.m.d f"}}</span>
                        <span>{{post.views}}</span>
                    </div>
                </span>
                <span class="user_post_comment">
                    <img src="{% static 'posts/img/comment.png' %}">
                    <div>{{post.comments.count}}</div>
                </span>
            </div>
        </a>
        {% endfor %}
    </div>
</div>
{% endblock content %}

{% block script %}
<script>
    document.querySelector(".bottom_icons").children.item(1).classList.add("set_bottom_black")
</script>
{% endblock script %}

templates/posts/post_update.html
{% extends 'base.html' %}
{% load static %}

<!-- 홈페이지 타이틀 -->
{% block title %}
글수정
{% endblock title %}


<!-- 개별적인 css/link태그 추가 -->
{% block css %}
<link rel="stylesheet" href="{% static 'posts/css/post_write.css' %}">
{% endblock css %}


{% block header %}
<div class="header__wrapper">
    <div class="header__leftbox">
        <img onclick="history.go(-1);" class="left_arrow" src="{% static 'core/img/left_arrow.png' %}"
            alt="left_arrow icon">
    </div>
    <div class="header__midbox">
        <span class="header__title">글수정</span>
    </div>
    <div class="header__rightbox"></div>
</div>
{% endblock header %}

{% block content %}
<form method="POST" class="post-form" enctype="multipart/form-data">

    {% csrf_token %}
    <div class="post_write_title">제목</div>
    <div class="post_write_title_box">{{ form.title }}</div>
    <div class="post_write_contents">내용</div>
    <div class="post_write_contents_box">{{ form.body }}</div>
    {{ form.user }}
    <!-- 글쓰기 이미지추가&등록 박스 -->
    <div class="post_write_submit_img_box"></div>
    <div class="post_write_img_box">
        <input type="file" name="photo" accept="image/*" id="id_photo">
        <div class="post_update_left">
            <input type="checkbox" name="photo-clear" id="photo-clear_id">
            <label for="photo-clear_id" class="image_delete">사진 삭제</label>
        </div>
    </div>
    <br>
    <div class="post_update_submit_bigbox">
        <input class="post_write_submit" type="submit" style="border-radius: 3px;" value="수정하기">
    </div>

</form>
{% endblock content %}

{% block script %}
<script>
    document.querySelector(".bottom_icons").children.item(1).classList.add("set_bottom_black")
</script>
{% endblock script %}

templates/posts/post_write.html
{% extends 'base.html' %}
{% load static %}

<!-- 홈페이지 타이틀 -->
{% block title %}
글쓰기
{% endblock title %}


<!-- 개별적인 css/link태그 추가 -->
{% block css %}
<link rel="stylesheet" href="{% static 'posts/css/post_write.css' %}">
{% endblock css %}


{% block header %}
<div class="header__wrapper">
    <div class="header__leftbox">
        <img onclick="history.go(-1);" class="left_arrow" src="{% static 'core/img/left_arrow.png' %}"
            alt="left_arrow icon">
    </div>
    <div class="header__midbox">
        <span class="header__title">글쓰기</span>
    </div>
    <div class="header__rightbox"></div>
</div>
{% endblock header %}


{% block content %}
<form method="POST" class="post-form" enctype="multipart/form-data" action="{% url 'posts:write' %}">

    {% csrf_token %}
    <div class="post_write_title">제목</div>
    <div style="border-top: solid 1px #eeeeee;border-bottom: solid 1px #eeeeee;" class="post_write_title_box">
        {{ form.title }}</div>
    <div class="post_write_contents">내용</div>
    <div class="post_write_contents_box">{{ form.body }}</div>
    <!-- 글쓰기 이미지추가&등록 박스 -->
    <div class="post_write_submit_img_box">
        <span class="post_write_img_box">
            {{ form.photo }}
            <!-- <img src="{% static 'posts/img/cameraimg.png' %}" class="post_write_camera"> -->
        </span>
        <input class="post_write_submit" type="submit" style="border-radius: 3px;" value="등록">
    </div>

</form>
{% endblock content %}

{% block script %}
<script>
    document.querySelector(".bottom_icons").children.item(1).classList.add("set_bottom_black")
</script>
{% endblock script %}

templates/posts/scrap_post_list.html
{% extends 'base.html' %}
{% load static %}

<!-- 홈페이지 타이틀 -->
{% block title %}
찜한 게시글
{% endblock title %}


<!-- 개별적인 css/link태그 추가 -->
{% block css %}
<link rel="stylesheet" href="{% static 'posts/css/post_list.css' %}">
{% endblock css %}


{% block header %}
<div class="header__wrapper">
    <div class="header__leftbox">
        <a href="{% url 'users:profile' %}"><img class="left_arrow" src="{% static 'core/img/left_arrow.png' %}"
                alt="left_arrow icon"></a>
    </div>
    <div class="header__midbox">
        <span class="header__title">찜한 게시글</span>
    </div>
    <div class="header__rightbox">
    </div>
</div>
{% endblock header %}


{% block content %}
{% if posts %}
<div class="post_list_bigbox">
    <div class="post_list_box">
        {% for post in posts %}
        <a href="{% url 'posts:detail' post.id %}">
            <div class="user_post_box">
                <span class="user_post_information">
                    <div class="user_post_title">{{post.title}}</div>
                    <div class="user_post_title_underbox">
                        <span>{{post.user.nickname}}</span>
                        <span>{{post.created_date|date:"Y.m.d f"}}</span>
                        <span>{{post.views}}</span>
                    </div>
                </span>
                <span class="user_post_comment">
                    <img src="{% static 'posts/img/comment.png' %}">
                    <div>{{post.comments.count}}</div>
                </span>
            </div>
        </a>
        {% endfor %}
    </div>
</div>
{% else %}
<div class="no_exist">
    <span>찜한 게시글이 없습니다!</span>
</div>
{% endif %}

{% endblock content %}