bakeries/urls.py
from django.urls import path
from . import views

app_name = "bakeries"

urlpatterns = [
    # 현재는 1-3)빵집리스트를 url로 나눠놨지만, html,css 작업이 끝나면 map에서 자바스크립트를 통해 페이지 새로고침 없이 보이게 할것임
    path("list/", views.bakery_list, name="list"),
    path("<int:bakery_id>/", views.bakery_detail, name="detail"),
    path("ajax_like/", views.ajax_like, name="ajax_like"),
    path("scon-data/", views.scon_sort_data),
    path("cake-data/", views.cake_sort_data),
    path("makarong-data/", views.makarong_sort_data),
    path("croffle-data/", views.croffle_sort_data),
    path("tart-data/", views.tart_sort_data),
    path("rank/", views.bakery_rank, name="rank"),
    # 나중에 데이터 갖고 작업할시에, <int:pk> 붙여서 유저별 좋아요리스트 구분해주자
    path("like/", views.bakery_like_list, name="like_list"),
    path("<int:bakery_id>/reviews/", views.bakery_review_list, name="review_list"),
    path("my/reviews/", views.user_review_list, name="user_review_list"),
    path("review-write/<int:bakery_id>/", views.review_write, name="review_write"),
    path("review-delete/<int:review_id>", views.review_delete, name="review_delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path("admin/", admin.site.urls),
]

urlpatterns = [
    path("zunsm29qmj/", admin.site.urls),
    path("map/", include("map.urls", namespace="map")),
    path("bakery/", include("bakeries.urls", namespace="bakeries")),
    path("post/", include("posts.urls", namespace="posts")),
    path("", include("users.urls", namespace="users")),
    url(
        r"media/(?P<path>.*)$",
        serve,
        {
            "document_root": settings.MEDIA_ROOT,
        },
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

map/urls.py
from django.urls import path
from . import views

app_name = "map"

urlpatterns = [
    path("", views.main_map_view, name="main_map"),
    path("region-api/", views.get_region_api, name="get_region_api"),
    path("bakery-list-api/", views.get_bakery_list_api, name="get_bakery_list_api"),
    path(
        "bakery-detail-api/", views.get_bakery_detail_api, name="get_bakery_detail_api"
    ),
    path(
        "bakery-detail-reviews-api/",
        views.get_bakery_detail_reviews_api,
        name="get_bakery_detail_reviews_api",
    ),
    path("bakery-delete-review/", views.ajax_delete_review, name="ajax_delete_review"),
]

posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path("", views.post_list, name="list"),
    # 프론트앤드 작업할때는 "1/"로 해놨지만, 나중에는 "<int:pk>/"로 변경예정"
    path("my/", views.post_my, name="my"),
    path("<int:post_id>/", views.post_detail, name="detail"),
    path("write/", views.post_write, name="write"),
    path("<int:post_id>/update/", views.post_update, name="update"),
    path("<int:post_id>/delete/", views.post_delete, name="delete"),
    path(
        "<int:post_id>/addcomment/",
        views.add_comment_to_post,
        name="add_comment_to_post",
    ),
    path(
        "<int:post_id>/comment/<int:comment_id>/delete",
        views.comment_delete,
        name="comment_delete",
    ),
    path("ajax_scrap/", views.ajax_scrap, name="ajax_scrap"),
    path("scrap/", views.scrap_post_list, name="scrap"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    # 배포시에는 index페이지 삭제
    # path("", views.index),
    path("user/profile/", views.profile_view, name="profile"),
    path("user/profile-update/", views.profile_update, name="profile_update"),
    path("", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("signup/", views.signup, name="signup"),
    path("user/login/kakao/", views.kakao_login, name="kakao-login"),
    path("user/login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
    path("imageupdate/", views.profileimage_update, name="imageupdate"),
    path("developers/", views.developers, name="developers"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <!-- meta 태그 모음 -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">


    <!-- 타이틀 -->
    <title>BROAD | {% block title %}{% endblock title %}</title>


    <link rel="shortcut icon" href="/favicon.ico">

    <!-- font 링크태그 모음 -->
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/gh/moonspam/NanumSquare@1.0/nanumsquare.css">

    <!-- css 링크태그 모음 -->
    <link rel="stylesheet" href="{% static 'core/css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'core/css/base.css' %}">
    {% block css %}
    <!-- 페이지별 개별적으로 css를 추가하는 부분 -->
    {% endblock css %}

    {% block head_script %}
    <!-- head태그에 들어갈 script를 추가하는 부분 -->
    {% endblock head_script %}
</head>

<body>
    <header class="header_height">
        {% block header %}
        <div class="header_wrap">
            <a href="{% url 'map:main_map' %}"><img class="logo_img" src="{% static 'core/img/logo.png' %}"
                    alt="logo image"></a>
            <div onclick="hiddenClick()" class="hidden_click jsHidden"></div>
        </div>
        <!-- <input class="header__searchbar" type="search" placeholder="검색어를 입력하세요"> -->
        {% endblock header %}
    </header>
    <div class="header_blank header_height"></div>
    <div class="content">
        {% block content %}
        <!-- 이 안에 들어가는 내용만 바뀌고, 나머지는 모든페이지에 적용됨 -->
        {% endblock content %}
    </div>
    {% block bottom_icons %}
    <footer>
    </footer>
    <div class="bottom_blank bottom_height"></div>
    <div class="bottom_icons bottom_height">
        <a href="{% url 'map:main_map' %}" class="buttom_icons__icon_wrap">
            <img src="{% static 'core/img/home.png' %}" alt="home icon">
        </a>
        <a href="{% url 'posts:list' %}" class="buttom_icons__icon_wrap">
            <img src="{% static 'core/img/community.png' %}" alt="community icon">
        </a>
        <a href="{% url 'bakeries:rank' %}" class="buttom_icons__icon_wrap">
            <img src="{% static 'core/img/rank.png' %}" alt="rank icon">
        </a>
        <a href="{% url 'bakeries:like_list' %}" class="buttom_icons__icon_wrap">
            <img src="{% static 'core/img/like.png' %}" alt="heart icon">
        </a>
        <a href="{% url 'users:profile' %}" class="buttom_icons__icon_wrap">
            <img style="width: 22px;" src="{% static 'core/img/blank_user.png' %}" alt="user icon">
        </a>
    </div>
    {% endblock bottom_icons %}

    <script src="{% static 'core/js/enlarge.js' %}"></script>
    <script src="{% static 'core/js/hiddenClick.js' %}"></script>
    {% block script %}
    <!-- JS/JQuery 스크립트 추가하는 부분 -->
    {% endblock script %}
</body>

</html>

templates/developers.html
{% extends 'base.html' %}
{% load static %}

<!-- 홈페이지 타이틀 -->
{% block title %}
개발자들
{% endblock title %}

<!-- 개별적인 css/link태그 추가 -->
{% block css %}
<link rel="stylesheet" href="{% static 'core/css/developers.css' %}">
{% endblock css %}

{% block header %}
<div class="header__wrapper">
    <div class="header__leftbox">
        <img onclick="history.go(-1);" class="left_arrow" src="{% static 'core/img/whiteback.png' %}"
            alt="left_arrow icon">
    </div>
    <div class="header__midbox">
    </div>
    <div class="header__rightbox">
        <!-- <img class="post_icon" src="{% static  'posts/img/menu.png' %}"> -->
    </div>
</div>
{% endblock header %}

{% block content %}
<h1>개발자들</h1>
<ul>
    <li>경상대학교 컴퓨터과학과 18학번 김은채</li>
    <li>경상대학교 물리학과 19학번 이가현</li>
    <li>경상대학교 화학과 19학번 윤지현</li>
    <li>경상대학교 한문학과 17학번 성은수</li>
</ul>
{% endblock content %}

{% block bottom_icons %}
<div class="bottom_icons bottom_height">
    <img src="{% static 'core/img/likelionlogo.png' %}" alt="likelion">
</div>
{% endblock bottom_icons %}

templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>URL 목차 페이지</title>
    <style>
        .title {
            font-size: 45px;
        }

        li {
            font-size: 30px;
            margin-bottom: 20px;
        }

        a {
            text-decoration-line: none;
        }
    </style>
</head>

<body>
    <h1 class="title">URL 목차 페이지(누르면 해당 작업페이지로 이동)</h1>
    <ul>
        <li><a href="{% url 'map:main_map' %}">1-1~2)지도</a></li>
        <hr>
        <li><a href="{% url 'bakeries:list' %}">1-3)빵집 리스트</a></li>
        <hr>
        <li><a href="{% url 'bakeries:review_list' 1 %}">1-5)리뷰 리스트</a></li>
        <hr>
        <li><a href="{% url 'bakeries:user_review_list' %}">1-6)내가 쓴 리뷰</a></li>
        <hr>
        <li><a href="{% url 'bakeries:review_write' 1 %}">1-7)리뷰 작성</a></li>
        <hr>
        <li><a href="{% url 'posts:list' %}">2-1)게시판(게시글 리스트)</a></li>
        <hr>
        <li><a href="{% url 'posts:detail' 1 %}">2-2)게시글 상세페이지</a></li>
        <hr>
        <li><a href="{% url 'posts:write' %}">2-3)게시판 글쓰기</a></li>
        <hr>
        <li><a href="{% url 'bakeries:rank' %}">3)빵집 랭킹</a></li>
        <hr>
        <li><a href="{% url 'users:profile' %}">4-1)프로필창</a></li>
        <hr>
        <li><a href="{% url 'users:profile_update' %}">4-2)프로필 수정</a></li>
        <hr>
        <li><a href="{% url 'users:login' %}">5-1)로그인</a></li>
        <hr>
        <li><a href="{% url 'users:signup' %}">5-2)회원가입</a></li>
        <hr>
        <li><a href="{% url 'bakeries:like_list' %}">6)좋아요빵집 리스트</a></li>
        <hr>
    </ul>
</body>

</html>