bakeries/urls.py
from django.urls import path
from . import views

app_name = "bakeries"

urlpatterns = [
    # 현재는 1-3)빵집리스트를 url로 나눠놨지만, html,css 작업이 끝나면 map에서 자바스크립트를 통해 페이지 새로고침 없이 보이게 할것임
    path("list/", views.bakery_list, name="list"),
    path("<int:bakery_id>/", views.bakery_detail, name="detail"),
    path("ajax_like/", views.ajax_like, name="ajax_like"),
    path("scon-data/", views.scon_sort_data),
    path("cake-data/", views.cake_sort_data),
    path("makarong-data/", views.makarong_sort_data),
    path("croffle-data/", views.croffle_sort_data),
    path("tart-data/", views.tart_sort_data),
    path("rank/", views.bakery_rank, name="rank"),
    # 나중에 데이터 갖고 작업할시에, <int:pk> 붙여서 유저별 좋아요리스트 구분해주자
    path("like/", views.bakery_like_list, name="like_list"),
    path("<int:bakery_id>/reviews/", views.bakery_review_list, name="review_list"),
    path("my/reviews/", views.user_review_list, name="user_review_list"),
    path("review-write/<int:bakery_id>/", views.review_write, name="review_write"),
    path("review-delete/<int:review_id>", views.review_delete, name="review_delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path("admin/", admin.site.urls),
]

urlpatterns = [
    path("zunsm29qmj/", admin.site.urls),
    path("map/", include("map.urls", namespace="map")),
    path("bakery/", include("bakeries.urls", namespace="bakeries")),
    path("post/", include("posts.urls", namespace="posts")),
    path("", include("users.urls", namespace="users")),
    url(
        r"media/(?P<path>.*)$",
        serve,
        {
            "document_root": settings.MEDIA_ROOT,
        },
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

map/urls.py
from django.urls import path
from . import views

app_name = "map"

urlpatterns = [
    path("", views.main_map_view, name="main_map"),
    path("region-api/", views.get_region_api, name="get_region_api"),
    path("bakery-list-api/", views.get_bakery_list_api, name="get_bakery_list_api"),
    path(
        "bakery-detail-api/", views.get_bakery_detail_api, name="get_bakery_detail_api"
    ),
    path(
        "bakery-detail-reviews-api/",
        views.get_bakery_detail_reviews_api,
        name="get_bakery_detail_reviews_api",
    ),
    path("bakery-delete-review/", views.ajax_delete_review, name="ajax_delete_review"),
]

posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path("", views.post_list, name="list"),
    # 프론트앤드 작업할때는 "1/"로 해놨지만, 나중에는 "<int:pk>/"로 변경예정"
    path("my/", views.post_my, name="my"),
    path("<int:post_id>/", views.post_detail, name="detail"),
    path("write/", views.post_write, name="write"),
    path("<int:post_id>/update/", views.post_update, name="update"),
    path("<int:post_id>/delete/", views.post_delete, name="delete"),
    path(
        "<int:post_id>/addcomment/",
        views.add_comment_to_post,
        name="add_comment_to_post",
    ),
    path(
        "<int:post_id>/comment/<int:comment_id>/delete",
        views.comment_delete,
        name="comment_delete",
    ),
    path("ajax_scrap/", views.ajax_scrap, name="ajax_scrap"),
    path("scrap/", views.scrap_post_list, name="scrap"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    # 배포시에는 index페이지 삭제
    # path("", views.index),
    path("user/profile/", views.profile_view, name="profile"),
    path("user/profile-update/", views.profile_update, name="profile_update"),
    path("", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("signup/", views.signup, name="signup"),
    path("user/login/kakao/", views.kakao_login, name="kakao-login"),
    path("user/login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
    path("imageupdate/", views.profileimage_update, name="imageupdate"),
    path("developers/", views.developers, name="developers"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import os
import random

# Create your models here.


# User모델의 avatar(프로필사진)의 경로설정 함수
def photo_path(instance, filename):
    basefilename, file_extension = os.path.splitext(filename)
    chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890"
    randomstr = "".join((random.choice(chars)) for x in range(10))
    return "user/avatar/{userid}/{randomstring}{ext}".format(
        userid=instance.id,
        basename=basefilename,
        randomstring=randomstr,
        ext=file_extension,
    )


class User(AbstractUser):
    nickname = models.CharField(max_length=10, default="", null=True, blank=True)
    avatar = models.ImageField(
        upload_to=photo_path, default="user/avatar/avatar_default.png"
    )
    is_social_login = models.BooleanField(default=False, blank=True, null=True)

users/forms.py
from django import forms
from .models import User
from django.contrib.auth import get_user_model


class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ["nickname"]
        widgets = {
            "nickname": forms.TextInput(
                attrs={"class": "profile_update_input", "placeholder": "선택입력"}
            ),
        }

    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"class": "profile_update_input", "placeholder": "비밀번호"}
        )
    )

    confirm_password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"class": "profile_update_input", "placeholder": "비밀번호 재입력"}
        )
    )

    def clean_confirm_password(self):
        password = self.cleaned_data.get("password")
        confirm_password = self.cleaned_data.get("confirm_password")
        if password != confirm_password:
            raise forms.ValidationError("비밀번호가 일치하지 않습니다")
        else:
            return password


class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.EmailInput(
            attrs={"class": "login_id_button", "placeholder": "이메일"}
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"class": "login_password_button", "placeholder": "비밀번호"}
        )
    )

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        try:
            user = User.objects.get(username=username)
            if user.check_password(password):
                return self.cleaned_data
            else:
                self.add_error("password", forms.ValidationError("비밀번호가 틀렸습니다"))
        except User.DoesNotExist:
            self.add_error("username", forms.ValidationError("계정이 존재하지 않습니다"))


class SignUpForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ["nickname"]
        widgets = {
            "nickname": forms.TextInput(
                attrs={"class": "signup_input", "placeholder": "선택입력"}
            ),
        }

    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={"class": "signup_input", "placeholder": "@example.com"}
        )
    )

    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"class": "signup_input", "placeholder": "비밀번호"}
        )
    )

    confirm_password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"class": "signup_input", "placeholder": "비밀번호 재입력"}
        )
    )

    def clean_email(self):
        try:
            User.objects.get(email=self.cleaned_data.get("email"))
            raise forms.ValidationError("이미 존재하는 계정입니다")
        except User.DoesNotExist:
            return self.cleaned_data.get("email")

    def clean_confirm_password(self):
        password = self.cleaned_data.get("password")
        confirm_password = self.cleaned_data.get("confirm_password")
        if password != confirm_password:
            raise forms.ValidationError("비밀번호가 일치하지 않습니다")
        else:
            return password


class UpdateProfileImageForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["avatar"]

users/views.py
import requests
import random
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.conf import settings
from .models import User
from .forms import UpdateProfileForm, UpdateProfileImageForm, LoginForm, SignUpForm


# Create your views here.


def index(request):
    return render(request, "index.html")


def login(request):
    if request.user.is_authenticated:
        return redirect("map:main_map")
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            auth_user = authenticate(request, username=username, password=password)
            if auth_user is not None:
                auth_login(request, auth_user)
                return redirect("map:main_map")
    else:
        form = LoginForm()
    return render(request, "users/login.html", {"form": form})


def logout(request):
    auth_logout(request)
    return redirect("users:login")


def signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get("email")
            username = email
            nickname = form.cleaned_data.get("nickname")
            if nickname is None:
                nickname = email.split("@")[0]
            password = form.cleaned_data.get("password")
            user = User.objects.create_user(
                username=username, nickname=nickname, email=email, password=password
            )
            auth_user = authenticate(request, username=username, password=password)
            if auth_user is not None:
                auth_login(request, auth_user)
                return redirect("map:main_map")
    else:
        form = SignUpForm()
    return render(request, "users/signup.html", {"form": form})


def profile_view(request):
    if request.user.is_anonymous:
        return redirect("users:login")
    return render(request, "users/my_profile.html")


def profile_update(request):
    user = User.objects.get(id=request.user.id)
    if request.method == "POST":
        form = UpdateProfileForm(request.POST, instance=user)
        if user.is_social_login:
            if request.POST.get("nickname") == "":
                pass
            else:
                user.nickname = request.POST.get("nickname")
                user.save()
            return redirect(reverse("users:profile"))
        if form.is_valid():
            username = request.user.username
            user = form.save(commit=False)
            user.nickname = form.cleaned_data.get("nickname")
            if form.cleaned_data.get("nickname") is None:
                user.nickname = request.user.email.split("@")[0]
            user.set_password(form.cleaned_data.get("password"))
            user.save()
            auth_login(request, user)
            return redirect(reverse("users:profile"))
    else:
        form = UpdateProfileForm(instance=user)
    return render(request, "users/profile_update.html", {"form": form})


# 카카오 소셜로그인
def kakao_login(request):
    client_id = settings.KAKAO_ID
    redirect_uri = f"https://{settings.MY_AWS_URL}/user/login/kakao/callback"
    return redirect(
        f"https://kauth.kakao.com/oauth/authorize?client_id={client_id}&redirect_uri={redirect_uri}&response_type=code"
    )


class KakaoException(Exception):
    pass


def kakao_callback(request):
    try:
        code = request.GET.get("code")
        client_id = settings.KAKAO_ID
        redirect_uri = f"https://{settings.MY_AWS_URL}/user/login/kakao/callback"
        token_request = requests.get(
            f"https://kauth.kakao.com/oauth/token?grant_type=authorization_code&client_id={client_id}&redirect_uri={redirect_uri}&code={code}"
        )
        token_json = token_request.json()
        error = token_json.get("error", None)
        if error is not None:
            raise KakaoException("접근할 수 없습니다.")
        access_token = token_json.get("access_token")
        profile_request = requests.get(
            "https://kapi.kakao.com/v2/user/me",
            headers={"Authorization": f"Bearer {access_token}"},
        )
        profile_json = profile_request.json()
        print(profile_json)
        kakao_account = profile_json.get("kakao_account")
        properties = profile_json.get("properties")
        nickname = properties.get("nickname")
        email = f"{profile_json.get('id')}@kakaologin.com"
        chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890"
        username = email
        try:
            user = User.objects.get(email=email)
        except User.DoesNotExist:
            user = User.objects.create(
                email=email, username=username, nickname=nickname, is_social_login=True
            )
            user.set_unusable_password()
            user.save()
        # messages.success(request, f"환영합니다, {user.nickname}님!")
        auth_login(request, user)
        return redirect(reverse("map:main_map"))
    except KakaoException as e:
        # messages.error(request, e)
        return redirect(reverse("users:login"))


def profileimage_update(request):
    user = User.objects.get(id=request.user.id)
    if request.method == "POST":
        form = UpdateProfileImageForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            user = form.save()
            return redirect("users:profile_update")
    else:
        form = UpdateProfileImageForm(instance=user)
        return render(request, "users/profileimage_form.html", {"form": form})


def developers(request):
    return render(request, "developers.html")

templates/users/login.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>BROAD | 로그인</title>
    <link rel="stylesheet" href="{% static 'core/css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'users/css/login.css' %}">
    <link rel="stylesheet" href="{% static 'users/css/mobile_reset.css' %}">
</head>

<body>
    <div class="login__midbox">
        <img class="login_logo" src="{% static 'core/img/login_logo.png' %}" alt="logo img">
        <form method="post">
            {% csrf_token %}
            <!-- <input class="login_id_button" type="text" name="user_id" id="user_id" placeholder="아이디"> -->
            {{form.username}}
            {% if form.username.errors %}
            {% for error in form.username.errors  %}
            {{error}}
            {% endfor %}
            {% endif %}
            <!-- <input class="login_password_button" type="text" name="user_password" id="user_password" placeholder="비밀번호"> -->
            {{form.password}}
            {% if form.password.errors %}
            {% for error in form.password.errors  %}
            {{error}}
            {% endfor %}
            {% endif %}
            <div class="login_two_link_box">
                <a href="#"><span class="password_change">비밀번호 변경</span></a>
                <a href="{% url 'map:main_map' %}"><span class="guest_login">게스트 로그인</span></a>
            </div>
            <input class="login_button" type="submit" value="로그인">
        </form>
        <div class="login_or_line">
            <hr>
            <span>또는</span>
            <hr>
        </div>
        <a href="{% url 'users:kakao-login' %}" class="social_login_button">
            <div class="social_login_left">
                <img class="kakao_logo" src="{% static 'users/img/kakao_logo.png' %}" alt="kakao logo">
            </div>
            <div class="social_login_mid">카카오 계정 로그인</div>
            <div class="social_login_right"></div>
        </a>
        <div class="signup_box">
            <span>계정이 없으신가요?</span>
            <a href="{% url 'users:signup' %}"><span class="signup_link">회원가입</span></a>
        </div>
    </div>

    <script src="{% static 'core/js/enlarge.js' %}"></script>
    <script src="{% static 'users/js/iphone5ScrollAvailable.js' %}"></script>
</body>

</html>

templates/users/my_profile.html
{% extends 'base.html' %}
{% load static %}

<!-- 홈페이지 타이틀 -->
{% block title %}
마이페이지
{% endblock title %}


<!-- 개별적인 css/link태그 추가 -->
{% block css %}
<link rel="stylesheet" href="{% static 'users/css/my_profile.css' %}">
{% endblock css %}


{% block header %}
<div class="header__wrapper">
    <div class="header__leftbox">
    </div>
    <div class="header__midbox">
        <span class="header__title">마이페이지</span>
    </div>
    <div class="header__rightbox">
    </div>
</div>
{% endblock header %}


{% block content %}
<div class="profile__top">
    <div class="myprofile">
        <div style="background-image: url({{user.avatar.url}});" class="profile__image"></div>
        <div class="profile__nickname">{{user.nickname}}</div>
    </div>
    <a class="profile__edit" href="{% url 'users:profile_update' %}"><span>프로필 수정</span></a>
</div>
<div class=line></div>
<div class="profile__middle">
    <a href="{% url 'bakeries:user_review_list' %}" class="profile__review"><img
            src="{% static 'users/img/write.png' %}">작성한 리뷰</a>
    <div class="profile__post">
        <h1>게시판</h1>
        <h2><a href="{% url 'posts:my' %}">내가 쓴 글</a></h2>
        <h2><a href="{% url 'posts:scrap' %}">스크랩한 게시글</a></h2>
    </div>
</div>
<div class="profile__bottom">
    <hr style="width:80%; height: 1px; border:none;border-top: 1px solid #cfcfcf;">
    <div class="profile__logout"><a href="{% url 'users:logout' %}">로그아웃</a></div>
</div>
{% endblock content %}

{% block script %}
<script>
    document.querySelector(".bottom_icons").children.item(4).classList.add("set_bottom_black")
</script>
{% endblock script %}

templates/users/profile_update.html
{% extends 'base.html' %}
{% load static %}

<!-- 홈페이지 타이틀 -->
{% block title %}
프로필 수정
{% endblock title %}


<!-- 개별적인 css/link태그 추가 -->
{% block css %}
<link rel="stylesheet" href="{% static 'users/css/profile_update.css' %}">
{% endblock css %}


{% block header %}
<div class="header__wrapper">
    <div class="header__leftbox">
        <a href="{% url 'users:profile' %}"><img class="left_arrow" src="{% static 'core/img/left_arrow.png' %}"
                alt="left_arrow icon"></a>
    </div>
    <div class="header__midbox">
        <span class="header__title">내 정보 수정</span>
    </div>
    <div class="header__rightbox">
    </div>
</div>
{% endblock header %}


{% block content %}
<form method="POST">
    {% csrf_token %}
    <div class="profile_update__top">
        <div style="background-image: url({{user.avatar.url}});" class="profile_update__image"></div>
        <a href="{% url 'users:imageupdate' %}"><img class="profile_update__imageupdate"
                src="https://www.vhv.rs/dpng/d/462-4623656_thumb-image-camera-icon-png-circle-transparent-png.png"></a>
    </div>
    <div class="profile_update_midbox">
        <div class="profile_update_sectionbox">
            <label for="user_email" class="profile_update_label">이메일<strong>(변경 불가)</strong></label>
            <div class="profile_update_input">{{user.email}}</div>
        </div>
        <div class="profile_update_sectionbox">
            <label for="user_nickname" class="profile_update_label">닉네임<strong>(선택)</strong></label>
            {{form.nickname}}
            {% if form.nickname.errors %}
            {% for error in form.nickname.errors  %}
            {{error}}
            {% endfor %}
            {% endif %}
        </div>
        {% if user.is_social_login %}
        {% else %}
        <div class="profile_update_sectionbox">
            <label for="user_password" class="profile_update_label">비밀번호</label>
            {{form.password}}
            {% if form.password.errors %}
            {% for error in form.password.errors  %}
            {{error}}
            {% endfor %}
            {% endif %}
            {{form.confirm_password}}
            {% if form.confirm_password.errors %}
            {% for error in form.confirm_password.errors  %}
            {{error}}
            {% endfor %}
            {% endif %}
        </div>
        {% endif %}
        <input class="signup_button" type="submit" value="확인">
    </div>
</form>
{% endblock content %}

{% block bottom_icons %}
{% endblock bottom_icons %}

{% block script %}
<script>
    document.querySelector(".bottom_icons").children.item(4).classList.add("set_bottom_black")
</script>
{% endblock script %}

templates/users/profileimage_form.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<style>
    .content {
        width: 100vw;
        height: 100vh;
        position: absolute;
        top: 0;
        display: flex;
        align-items: center;
        justify-content: center;
    }

    form {
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        height: 100px;
    }

    .profile_image_submit {
        background-color: #5d2c1d;
        border: none;
        border-radius: 5px;
        color: white;
        padding: 8px 12px;
        margin-right: 10px;
    }
</style>
{% endblock css %}

{% block title %}
프로필 수정
{% endblock title %}

{% block header %}
<div class="header__wrapper">
    <div class="header__leftbox">
        <a href="{% url 'users:profile_update' %}"><img class="left_arrow" src="{% static 'core/img/left_arrow.png' %}"
                alt="left_arrow icon"></a>
    </div>
    <div class="header__midbox">
        <span class="header__title">프로필 이미지 변경</span>
    </div>
    <div class="header__rightbox">
    </div>
</div>
{% endblock header %}
{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="avatar" accept="image/*" id="id_avatar">
    <input class="profile_image_submit" type="submit" style="border-radius: 3px;" value="등록">
</form>
{% endblock content %}

{% block bottom_icons %}
{% endblock bottom_icons %}

templates/users/signup.html
{% extends 'base.html' %}
{% load static %}

<!-- 홈페이지 타이틀 -->
{% block title %}
회원가입
{% endblock title %}


<!-- 개별적인 css/link태그 추가 -->
{% block css %}
<link rel="stylesheet" href="{% static 'users/css/signup.css' %}">
{% endblock css %}


{% block header %}
<div class="header__wrapper">
    <div class="header__leftbox">
        <img onclick="history.go(-1);" class="left_arrow" src="{% static 'core/img/left_arrow.png' %}"
            alt="left_arrow icon">
    </div>
    <div class="header__midbox">
        <span class="header__title">회원가입</span>
    </div>
    <div class="header__rightbox">
    </div>
</div>
{% endblock header %}


{% block content %}
<form method="POST">
    {% csrf_token %}
    <div class="signup_midbox">
        <div class="signup_sectionbox">
            <label for="user_email" class="signup_label">브로드 계정</label>
            <!-- <input class="signup_input" type="email" name="user_email" id="user_email" placeholder="@example.com"> -->
            {{form.email}}
            {% if form.email.errors %}
            {% for error in form.email.errors  %}
            {{error}}
            {% endfor %}
            {% endif %}
        </div>
        <div class="signup_sectionbox">
            <label for="user_nickname" class="signup_label">닉네임<strong>(선택)</strong></label>
            <!-- <input class="signup_input" type="text" name="user_nickname" id="user_nickname" placeholder="선택입력"> -->
            {{form.nickname}}
            {% if form.nickname.errors %}
            {% for error in form.nickname.errors  %}
            {{error}}
            {% endfor %}
            {% endif %}
        </div>
        <div class="signup_sectionbox">
            <label for="user_password" class="signup_label">비밀번호</label>
            <!-- <input class="signup_input" type="password" name="user_password" id="user_password"
                placeholder="비밀번호(8~32자리)"> -->
            {{form.password}}
            {% if form.password.errors %}
            {% for error in form.password.errors  %}
            {{error}}
            {% endfor %}
            {% endif %}
            <!-- <input class="signup_input" type="password" name="user_confirm_password" id="user_confirm_password"
                placeholder="비밀번호 재입력"> -->
            {{form.confirm_password}}
            {% if form.confirm_password.errors %}
            {% for error in form.confirm_password.errors  %}
            {{error}}
            {% endfor %}
            {% endif %}
        </div>
        <input class="signup_button" type="submit" value="회원가입">
    </div>
</form>
{% endblock content %}


{% block bottom_icons %}
{% endblock bottom_icons %}